import Arena from "./arena.js";
import Uniform from "./uniform.js";
import Cellular from "./cellular.js";
import Digger from "./digger.js";
import EllerMaze from "./ellermaze.js";
import DividedMaze from "./dividedmaze.js";
import IceyMaze from "./iceymaze.js";
import Rogue from "./rogue.js";
import Irregular from "./irregular.js";
declare const _default: {
    Arena: typeof Arena;
    Uniform: typeof Uniform;
    Cellular: typeof Cellular;
    Digger: typeof Digger;
    EllerMaze: typeof EllerMaze;
    DividedMaze: typeof DividedMaze;
    IceyMaze: typeof IceyMaze;
    Rogue: typeof Rogue;
    Irregular: typeof Irregular;
};
export default _default;
